
import __ASTRO_IMAGE_IMPORT_1N4YXq from "../../assets/images/projects/cartoonify/thumbnail.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fcartoonify.mdx";
import __ASTRO_IMAGE_IMPORT_Z1OqIn4 from "../../assets/images/projects/ev-range-pred/thumbnail.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fev-range-pred.mdx";
import __ASTRO_IMAGE_IMPORT_Z5ekoa from "../../assets/images/projects/grammar-ninja/thumbnail.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fgrammar-ninja.mdx";
import __ASTRO_IMAGE_IMPORT_Z2v930o from "../../assets/images/projects/dinov2cpp/thumbnail.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fdinov2cpp.mdx";
import __ASTRO_IMAGE_IMPORT_1NYwQm from "../../assets/images/projects/graphic-memoir-analysis/thumbnail.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fgraphic-memoir-analysis.mdx";
import __ASTRO_IMAGE_IMPORT_1GN49r from "../../assets/images/projects/hand-gesture-recognition/thumbnail.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fhand-gesture-recognition.mdx";
import __ASTRO_IMAGE_IMPORT_ZYaxeP from "../../assets/images/projects/human-connectome/thumbnail.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fhuman-connectome.mdx";
import __ASTRO_IMAGE_IMPORT_2upGna from "../../assets/images/projects/motion-gpt1.5/thumbnail.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fmotion-gpt1.5.mdx";
import __ASTRO_IMAGE_IMPORT_Gat1m from "../../assets/images/projects/object-tracking/thumbnail.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fobject-tracking.mdx";
import __ASTRO_IMAGE_IMPORT_dM8wW from "../../assets/images/projects/plantify-dr/thumbnail.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fplantify-dr.mdx";
import __ASTRO_IMAGE_IMPORT_Z1sWXVC from "../../assets/images/projects/reasoning-slms/thumbnail.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Freasoning-slms.mdx";
import __ASTRO_IMAGE_IMPORT_Z1lbCQQ from "../../assets/images/projects/sketch-n-solve/thumbnail.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fsketch-n-solve.mdx";
import __ASTRO_IMAGE_IMPORT_139bIV from "../../assets/images/projects/responsible-ai-audit/thumbnail.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fresponsible-ai-audit.mdx";
export default new Map([["../../assets/images/projects/cartoonify/thumbnail.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fcartoonify.mdx", __ASTRO_IMAGE_IMPORT_1N4YXq], ["../../assets/images/projects/ev-range-pred/thumbnail.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fev-range-pred.mdx", __ASTRO_IMAGE_IMPORT_Z1OqIn4], ["../../assets/images/projects/grammar-ninja/thumbnail.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fgrammar-ninja.mdx", __ASTRO_IMAGE_IMPORT_Z5ekoa], ["../../assets/images/projects/dinov2cpp/thumbnail.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fdinov2cpp.mdx", __ASTRO_IMAGE_IMPORT_Z2v930o], ["../../assets/images/projects/graphic-memoir-analysis/thumbnail.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fgraphic-memoir-analysis.mdx", __ASTRO_IMAGE_IMPORT_1NYwQm], ["../../assets/images/projects/hand-gesture-recognition/thumbnail.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fhand-gesture-recognition.mdx", __ASTRO_IMAGE_IMPORT_1GN49r], ["../../assets/images/projects/human-connectome/thumbnail.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fhuman-connectome.mdx", __ASTRO_IMAGE_IMPORT_ZYaxeP], ["../../assets/images/projects/motion-gpt1.5/thumbnail.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fmotion-gpt1.5.mdx", __ASTRO_IMAGE_IMPORT_2upGna], ["../../assets/images/projects/object-tracking/thumbnail.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fobject-tracking.mdx", __ASTRO_IMAGE_IMPORT_Gat1m], ["../../assets/images/projects/plantify-dr/thumbnail.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fplantify-dr.mdx", __ASTRO_IMAGE_IMPORT_dM8wW], ["../../assets/images/projects/reasoning-slms/thumbnail.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Freasoning-slms.mdx", __ASTRO_IMAGE_IMPORT_Z1sWXVC], ["../../assets/images/projects/sketch-n-solve/thumbnail.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fsketch-n-solve.mdx", __ASTRO_IMAGE_IMPORT_Z1lbCQQ], ["../../assets/images/projects/responsible-ai-audit/thumbnail.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fresponsible-ai-audit.mdx", __ASTRO_IMAGE_IMPORT_139bIV]]);
		