
export default new Map([
["src/content/blog/ai-coding-infrastructure.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fai-coding-infrastructure.mdx&astroContentModuleFlag=true")],
["src/content/blog/context-engineering-ai-ides.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fcontext-engineering-ai-ides.mdx&astroContentModuleFlag=true")],
["src/content/blog/atomic-workflow.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fatomic-workflow.mdx&astroContentModuleFlag=true")],
["src/content/blog/context-engineering-cheat-sheet.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fcontext-engineering-cheat-sheet.mdx&astroContentModuleFlag=true")],
["src/content/blog/memorization-generalization-and-reasoning.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fmemorization-generalization-and-reasoning.mdx&astroContentModuleFlag=true")],
["src/content/projects/cartoonify.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Fcartoonify.mdx&astroContentModuleFlag=true")],
["src/content/blog/self-evolving-llm-agents.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fself-evolving-llm-agents.mdx&astroContentModuleFlag=true")],
["src/content/projects/dinov2cpp.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Fdinov2cpp.mdx&astroContentModuleFlag=true")],
["src/content/projects/ev-range-pred.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Fev-range-pred.mdx&astroContentModuleFlag=true")],
["src/content/projects/grammar-ninja.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Fgrammar-ninja.mdx&astroContentModuleFlag=true")],
["src/content/projects/graphic-memoir-analysis.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Fgraphic-memoir-analysis.mdx&astroContentModuleFlag=true")],
["src/content/projects/hand-gesture-recognition.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Fhand-gesture-recognition.mdx&astroContentModuleFlag=true")],
["src/content/projects/human-connectome.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Fhuman-connectome.mdx&astroContentModuleFlag=true")],
["src/content/projects/motion-gpt1.5.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Fmotion-gpt1.5.mdx&astroContentModuleFlag=true")],
["src/content/projects/object-tracking.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Fobject-tracking.mdx&astroContentModuleFlag=true")],
["src/content/projects/plantify-dr.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Fplantify-dr.mdx&astroContentModuleFlag=true")],
["src/content/projects/reasoning-slms.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Freasoning-slms.mdx&astroContentModuleFlag=true")],
["src/content/projects/responsible-ai-audit.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Fresponsible-ai-audit.mdx&astroContentModuleFlag=true")],
["src/content/projects/sketch-n-solve.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Fsketch-n-solve.mdx&astroContentModuleFlag=true")]]);
		